name: push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: gcc vcd.c -o vcd
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_FILES: vcd
      run: |
        ls -al
        RELEASE_TAG="$(date +%y%m%d)"
        curl -sL -XPOST -d '{"tag_name": "'$RELEASE_TAG'"}' \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H 'Content-Type: application/json' \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
        RELEASE_ID=$(curl -svL https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$RELEASE_TAG | jq .id)
        for RELEASE_FILE in $RELEASE_FILES ; do
          curl -sL -XPOST -T ${RELEASE_FILE}* \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type:application/octet-stream" \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/$RELEASE_ID/assets?&name=$RELEASE_FILE-$OS"
        done
      shell: bash
